-- 2026-08-29 — Fase C, fatia 2: dívidas (saldo devedor) por instituição
--
-- Brief: Projetos/PRADEX/briefs/2026-08-29_desktop-cartoes-categorias-e-bancos.md (§4)
-- Depende da migration 2026-08-29_bancos.sql (fatia 1).
--
-- Por que uma tabela nova em vez de estender `Lancamentos`: o que existe hoje é a
-- categoria de despesa "Financiamentos" em fp_despesas — a PARCELA MENSAL. Isso é
-- fluxo. Dívida é saldo: quanto ainda se deve agora. Misturar os dois contaminaria
-- todo cálculo que já roda sobre `Lancamentos` (dashboard, gastos por categoria,
-- Diagnóstico FP), e a matemática do FP está fora de escopo.
--
-- Esta migration NÃO migra nada de fp_despesas: a parcela continua sendo despesa,
-- e o saldo passa a ser dívida. São dados diferentes sobre o mesmo compromisso.

create table if not exists public.dividas (
  id                  bigint generated by default as identity primary key,
  user_id             uuid not null default auth.uid() references auth.users(id) on delete cascade,
  -- Nullable pelo mesmo motivo de cartoes.banco_id: excluir um banco não pode
  -- apagar a dívida junto, e existe dívida sem instituição (empréstimo com pessoa).
  banco_id            bigint references public.bancos(id) on delete set null,
  descricao           text not null,
  -- O número que faltava pro patrimônio líquido existir.
  saldo_devedor       numeric(14,2) not null default 0,
  -- Opcionais: quem não souber preencher ainda tem o saldo, que é o essencial.
  valor_parcela       numeric(14,2),
  parcelas_restantes  integer,
  taxa_juros_mensal   numeric(6,3), -- em % ao mês, ex.: 1.990
  removida            boolean not null default false,
  criado_em           timestamptz not null default now(),

  constraint dividas_saldo_nao_negativo check (saldo_devedor >= 0),
  constraint dividas_parcelas_nao_negativas check (parcelas_restantes is null or parcelas_restantes >= 0)
);

create index if not exists dividas_user_id_idx on public.dividas (user_id);
create index if not exists dividas_banco_id_idx on public.dividas (banco_id);

alter table public.dividas enable row level security;

drop policy if exists "dividas_select_own" on public.dividas;
create policy "dividas_select_own" on public.dividas
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "dividas_insert_own" on public.dividas;
create policy "dividas_insert_own" on public.dividas
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "dividas_update_own" on public.dividas;
create policy "dividas_update_own" on public.dividas
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "dividas_delete_own" on public.dividas;
create policy "dividas_delete_own" on public.dividas
  for delete to authenticated using (user_id = auth.uid());

-- ============================================================================
-- Conferência
-- ============================================================================
--   select b.nome as banco, d.descricao, d.saldo_devedor, d.valor_parcela
--     from public.dividas d left join public.bancos b on b.id = d.banco_id
--    where not d.removida
--    order by b.nome nulls last, d.saldo_devedor desc;
--
--   -- total de passivos:
--   select sum(saldo_devedor) from public.dividas where not removida;
