-- 2026-09-12 — Orçamento por categoria (teto mensal)
--
-- Spec: Chave Mestre, Projetos/PRADEX/orcamento-e-disciplina.md
--
-- O teto é o que destrava o resto: vira o componente de maior peso do score de
-- disciplina (45 de 145) e liga 2 dos 5 gatilhos do modo caos, que hoje não podem
-- disparar porque não existe teto pra estourar.
--
-- Recurso do plano 'essencial' pra cima. O ENFORCEMENT do plano NÃO mora aqui —
-- mora no front (src/lib/plano.js) e, pro agente, na Edge Function. RLS aqui só
-- garante que ninguém lê nem escreve o teto de outra pessoa.

-- ============================================================================
-- 1. Tabela
-- ============================================================================
create table if not exists public.orcamentos (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  categoria   text not null,
  -- Teto do mês, em reais. numeric, nunca float: dinheiro não arredonda sozinho.
  limite      numeric(12,2) not null check (limite > 0),
  -- Primeiro dia do mês de competência. Guardar o mês como DATE (e não ano+mês em
  -- duas colunas) deixa comparação e ordenação triviais.
  mes         date not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists orcamentos_user_mes_idx
  on public.orcamentos (user_id, mes);

-- Um teto por categoria por mês. `lower()` porque a categoria é texto livre vindo
-- do cadastro do usuário — "Delivery" e "delivery" são a mesma coisa.
create unique index if not exists orcamentos_user_mes_categoria_idx
  on public.orcamentos (user_id, mes, lower(categoria));

-- O mês é sempre o dia 1. Sem isto, 2026-09-01 e 2026-09-15 viram dois orçamentos
-- distintos do mesmo mês e a unique acima não protege nada.
create or replace function public.orcamentos_normaliza()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.mes := date_trunc('month', new.mes)::date;
  new.categoria := btrim(new.categoria);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_orcamentos_normaliza on public.orcamentos;
create trigger trg_orcamentos_normaliza
  before insert or update on public.orcamentos
  for each row execute function public.orcamentos_normaliza();

-- ============================================================================
-- 2. RLS
-- ============================================================================
alter table public.orcamentos enable row level security;

drop policy if exists "orcamentos_select_own" on public.orcamentos;
create policy "orcamentos_select_own" on public.orcamentos
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "orcamentos_insert_own" on public.orcamentos;
create policy "orcamentos_insert_own" on public.orcamentos
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "orcamentos_update_own" on public.orcamentos;
create policy "orcamentos_update_own" on public.orcamentos
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "orcamentos_delete_own" on public.orcamentos;
create policy "orcamentos_delete_own" on public.orcamentos
  for delete to authenticated using (user_id = auth.uid());

-- ============================================================================
-- 3. Rede de segurança: versiona a proteção que hoje só existe no banco vivo
-- ============================================================================
-- A auditoria de 2026-09-12 (briefs/2026-09-12_auditoria-seguranca.md) achou que
-- `fp_perfil`, `Lancamentos`, `cartoes` e `categorias` NÃO têm RLS em migration
-- nenhuma. Produção está protegida — verificado contra a API com a anon key: leitura
-- devolve [] e escrita bate em "violates row-level security policy" —, mas um banco
-- recriado a partir destas migrations nasceria ABERTO.
--
-- Este bloco é deliberadamente conservador: só age se a tabela existir e NÃO tiver
-- nenhuma policy. Em produção ele não faz nada (as policies já estão lá); num banco
-- novo, ele fecha a porta. Nunca sobrescreve policy existente — se a de produção for
-- diferente da que eu escreveria, ela vence.
do $$
declare
  t text;
  alvos text[] := array['fp_perfil', 'Lancamentos', 'cartoes', 'categorias'];
begin
  foreach t in array alvos loop
    if not exists (
      select 1 from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relname = t and c.relkind = 'r'
    ) then
      raise notice 'orcamentos.sql: tabela %.% nao existe, pulando', 'public', t;
      continue;
    end if;

    execute format('alter table public.%I enable row level security', t);

    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = t) then
      raise notice 'orcamentos.sql: % ja tem policy, nao mexo', t;
      continue;
    end if;

    raise notice 'orcamentos.sql: % SEM policy — criando as quatro por user_id', t;
    execute format($f$create policy %I on public.%I for select to authenticated using (user_id = auth.uid())$f$, t || '_select_own', t);
    execute format($f$create policy %I on public.%I for insert to authenticated with check (user_id = auth.uid())$f$, t || '_insert_own', t);
    execute format($f$create policy %I on public.%I for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())$f$, t || '_update_own', t);
    execute format($f$create policy %I on public.%I for delete to authenticated using (user_id = auth.uid())$f$, t || '_delete_own', t);
  end loop;
end $$;

-- Mesma lógica pra RPC: `agente_aplicar_acoes` é SECURITY DEFINER e aceita p_user_id
-- do chamador sem comparar com auth.uid(). Em produção o EXECUTE já está revogado
-- (a chamada devolve 42501), mas isso também não está versionado em lugar nenhum.
-- Revogar de novo é idempotente e barato.
do $$
begin
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
              where n.nspname = 'public' and p.proname = 'agente_aplicar_acoes') then
    revoke execute on function public.agente_aplicar_acoes(uuid, jsonb) from public, anon, authenticated;
  end if;
end $$;

-- ============================================================================
-- Conferir depois de rodar
-- ============================================================================
--   select tablename, policyname from pg_policies
--    where schemaname = 'public' and tablename in
--      ('orcamentos','fp_perfil','Lancamentos','cartoes','categorias')
--    order by tablename, policyname;
--
--   -- deve devolver zero linhas (ninguém além do dono executa):
--   select grantee from information_schema.routine_privileges
--    where routine_name = 'agente_aplicar_acoes' and grantee in ('anon','authenticated','PUBLIC');
