-- 2026-08-29 — Fase C, fatia 1: bancos como entidade raiz
--
-- Brief: Projetos/PRADEX/briefs/2026-08-29_desktop-cartoes-categorias-e-bancos.md (§4)
-- Decisão do Lucas (29/08): banco vira entidade própria, com os cartões, dívidas e
-- investimentos pendurados nele. Esta migration cobre SÓ a tabela e o vínculo com
-- cartões — dívidas e investimentos vêm em migrations separadas, uma coisa de cada vez.
--
-- Nada aqui é destrutivo: a coluna nova em `cartoes` é nullable, então todo cartão
-- que já existe continua funcionando sem banco.

-- ============================================================================
-- bancos — instituições onde o usuário tem conta
-- ============================================================================
create table if not exists public.bancos (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nome          text not null,
  -- Código COMPE (3 dígitos, ex.: '341' = Itaú). Nulo quando o usuário escolheu
  -- "Outro" e digitou o nome à mão — a lista do app é semi-fechada, não exaustiva.
  codigo_compe  text,
  -- Soft-delete: o mesmo padrão de `categorias`. Um banco escondido não pode sumir
  -- de vez enquanto houver cartão/dívida apontando pra ele.
  removido      boolean not null default false,
  criado_em     timestamptz not null default now()
);

create index if not exists bancos_user_id_idx on public.bancos (user_id);

-- Um usuário não cadastra o mesmo banco duas vezes. Só vale pros ativos: se ele
-- remover e recadastrar, a linha antiga fica lá com removido = true.
create unique index if not exists bancos_user_nome_ativo_idx
  on public.bancos (user_id, lower(nome))
  where removido = false;

alter table public.bancos enable row level security;

drop policy if exists "bancos_select_own" on public.bancos;
create policy "bancos_select_own" on public.bancos
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "bancos_insert_own" on public.bancos;
create policy "bancos_insert_own" on public.bancos
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "bancos_update_own" on public.bancos;
create policy "bancos_update_own" on public.bancos
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "bancos_delete_own" on public.bancos;
create policy "bancos_delete_own" on public.bancos
  for delete to authenticated using (user_id = auth.uid());

-- ============================================================================
-- cartoes.banco_id — vínculo opcional
-- ============================================================================
-- on delete set null: excluir um banco não pode levar os cartões junto. O cartão
-- volta a ser "sem banco", que é exatamente o estado de todos eles hoje.
alter table public.cartoes
  add column if not exists banco_id bigint references public.bancos(id) on delete set null;

create index if not exists cartoes_banco_id_idx on public.cartoes (banco_id);

-- ============================================================================
-- Conferência
-- ============================================================================
--   select id, nome, codigo_compe, removido from public.bancos order by nome;
--   select c.nome as cartao, b.nome as banco
--     from public.cartoes c left join public.bancos b on b.id = c.banco_id
--    order by b.nome nulls first, c.nome;
