-- 2026-09-05 — Suporte ao webhook da Cakto (Fase 1)
--
-- Brief: Projetos/PRADEX/briefs/2026-09-05_saas-planos-webhook-paywall.md (Fase 1)
-- Depende de 2026-09-05_fp_perfil_planos.sql (colunas plano / plano_ate).
--
-- Três peças: log de eventos (idempotência + auditoria), fila de pendências pra
-- compra sem conta correspondente, e o lookup de e-mail → auth.users que a Edge
-- Function precisa (auth.users não é exposto via PostgREST).

-- ============================================================================
-- cakto_eventos — todo evento recebido, processado ou não
-- ============================================================================
-- A unique (event, event_id) é a idempotência: a Cakto reentrega o mesmo evento
-- em falha de rede (5s, 1m, 2m30, 6m, 30m) e o painel ainda tem reenvio manual.
-- Chaveia por (event, event_id) e não só por event_id porque o mesmo pedido dispara
-- eventos diferentes (purchase_approved e depois subscription_renewed).
--
-- `payload` guarda o corpo cru. É de propósito: a doc da Cakto não especifica os
-- campos do objeto `subscription`, então o primeiro evento real é o que vai revelar
-- o formato — sem isso a gente estaria adivinhando (ver plano_ate na Edge Function).
create table if not exists public.cakto_eventos (
  id                    bigint generated by default as identity primary key,
  event                 text not null,
  event_id              text not null,
  resultado             text not null,
  email                 text,
  plano                 text,
  user_id               uuid references auth.users(id) on delete set null,
  detalhe               text,
  payload               jsonb not null,
  recebido_em           timestamptz not null default now(),
  constraint cakto_eventos_unicos unique (event, event_id),
  constraint cakto_eventos_resultado_check check (resultado in
    ('aplicado', 'revogado', 'ignorado', 'sem_conta', 'erro'))
);

create index if not exists cakto_eventos_recebido_em_idx
  on public.cakto_eventos (recebido_em desc);

-- Sem policy nenhuma de propósito: só service_role (que ignora RLS) escreve e lê.
-- Tem e-mail e valor de compra de cliente aqui dentro — nada disso vaza pro anon.
alter table public.cakto_eventos enable row level security;

-- ============================================================================
-- pendencias_assinatura — comprou mas não tem conta no app
-- ============================================================================
-- Brief, item 4: não falhar o webhook quando o e-mail da compra não bate com
-- nenhuma conta. Grava aqui e o Lucas amarra depois (runbook no fim do arquivo).
create table if not exists public.pendencias_assinatura (
  id           bigint generated by default as identity primary key,
  email        text not null,
  plano        text not null,
  event        text not null,
  event_id     text not null,
  motivo       text not null,
  resolvido    boolean not null default false,
  resolvido_em timestamptz,
  criado_em    timestamptz not null default now(),
  constraint pendencias_assinatura_plano_check check (plano in ('essencial', 'assistente')),
  constraint pendencias_assinatura_motivo_check check (motivo in ('sem_auth_user', 'sem_fp_perfil'))
);

create index if not exists pendencias_assinatura_abertas_idx
  on public.pendencias_assinatura (email) where not resolvido;

alter table public.pendencias_assinatura enable row level security;

-- ============================================================================
-- fp_user_id_por_email — lookup que a Edge Function usa
-- ============================================================================
-- auth.users não sai pelo PostgREST, e listUsers() da Admin API é paginado (varrer
-- a base inteira a cada webhook seria absurdo). SECURITY DEFINER pra enxergar o
-- schema auth, com EXECUTE revogado de anon/authenticated: solto, isso viraria um
-- oráculo de "esse e-mail tem conta aqui?" pra qualquer visitante.
create or replace function public.fp_user_id_por_email(p_email text)
returns uuid
language sql
security definer
stable
set search_path = public, auth, pg_temp
as $$
  select id from auth.users where lower(email) = lower(trim(p_email)) limit 1;
$$;

revoke all on function public.fp_user_id_por_email(text) from public;
revoke all on function public.fp_user_id_por_email(text) from anon;
revoke all on function public.fp_user_id_por_email(text) from authenticated;
grant execute on function public.fp_user_id_por_email(text) to service_role;

-- ============================================================================
-- Runbook
-- ============================================================================
-- Pendências abertas (comprou e não tinha conta):
--
--   select email, plano, event, criado_em from public.pendencias_assinatura
--    where not resolvido order by criado_em;
--
-- Amarrar uma pendência depois que a pessoa criou a conta:
--
--   update public.fp_perfil set plano = 'assistente', plano_ate = now() + interval '30 days'
--    where user_id = public.fp_user_id_por_email('cliente@exemplo.com');
--   update public.pendencias_assinatura set resolvido = true, resolvido_em = now()
--    where email = 'cliente@exemplo.com' and not resolvido;
--
-- Últimos eventos da Cakto (debug do webhook):
--
--   select recebido_em, event, resultado, email, plano, detalhe
--     from public.cakto_eventos order by recebido_em desc limit 20;
--
-- Ver o payload cru de um evento (é aqui que se descobre o formato do objeto
-- `subscription`, que a doc da Cakto não especifica):
--
--   select payload -> 'data' -> 'subscription' from public.cakto_eventos
--    where event like 'subscription%' order by recebido_em desc limit 5;
--
-- Eventos que falharam (a Cakto NÃO reentrega erro 5xx — reenvio é manual no painel):
--
--   select recebido_em, event, event_id, detalhe from public.cakto_eventos
--    where resultado = 'erro' order by recebido_em desc;
