-- 2026-09-19 — METAS: dificuldade declarada, marcos de progresso e pontos
--
-- Brief: Chave Mestre, Projetos/PRADEX/briefs/2026-09-19_ranking-e-pontuacao-de-metas.md
--
-- O PROBLEMA (Lucas): "eu coloquei uma meta no meu app, casamento, 100 mil. Até
-- juntar 100 mil o cara nunca será recompensado por ter chegado?"
--
-- Até aqui existia UM evento de vitória: `concluida_em`. Numa meta de R$ 100.000 isso
-- é um silêncio de dois anos — a pessoa faz a coisa certa todo mês e o produto não
-- diz nada. Esta migration cria os eventos do caminho.
--
-- ============================================================================
-- As três decisões que explicam o schema
-- ============================================================================
--
-- 1. DIFICULDADE É DECLARADA PELO DONO. O app não lê conta nem renda, e a mesma meta
--    de R$ 5.000 é trivial pra um e brutal pra outro. Só o dono sabe. Na tela, cada
--    opção descreve o MÊS da pessoa e não o prêmio ("vai doer todo mês até eu chegar
--    lá") — é o que faz a resposta sair honesta sem ninguém policiando.
--
-- 2. OS PONTOS VÊM DOS MARCOS, não do % contínuo. Assim o placar só muda quando
--    alguém conquista alguma coisa, e não a cada real guardado.
--
-- 3. CADA MARCO É UMA LINHA COM DATA, e não um contador na meta. É o que mantém
--    aberta a saída pro problema que o Lucas viu — "os novos nunca chegam nos
--    primeiros usuários" —, que é um ranking POR MÊS, que zera. Escolher entre mensal
--    e acumulado pode ficar pra depois; ter a data não pode, porque reconstruir o
--    passado exigiria varrer lançamento por lançamento de todo mundo, e a data de
--    quem apagou lançamento não volta nunca.
--
-- ============================================================================
-- 1. metas: dificuldade e o progresso que não desce
-- ============================================================================
alter table public.metas
  add column if not exists dificuldade text not null default 'moderada';

-- `drop`+`add` e não `add if not exists`: constraint não tem IF NOT EXISTS e precisa
-- ser idempotente pra migration poder rodar duas vezes sem explodir.
alter table public.metas drop constraint if exists metas_dificuldade_valida;
alter table public.metas
  add constraint metas_dificuldade_valida
  check (dificuldade in ('facil', 'moderada', 'dificil'));

-- Maior progresso JÁ alcançado (0..1), não o atual. Mesmo princípio do `concluida_em`:
-- resgatar não desfaz conquista, senão o placar piscaria e a comemoração viria duas
-- vezes pela mesma coisa.
alter table public.metas
  add column if not exists progresso_max numeric(6,4) not null default 0;

-- Maior marco já celebrado. Existe pra tela saber, numa comparação, que apareceu
-- marco novo — sem precisar ler a tabela de marcos a cada render.
alter table public.metas
  add column if not exists marco_max smallint not null default 0;

-- ============================================================================
-- 2. meta_marcos — um evento por conquista, com data
-- ============================================================================
create table if not exists public.meta_marcos (
  id          bigint generated by default as identity primary key,
  meta_id     bigint not null references public.metas (id) on delete cascade,
  -- Desnormalizado de propósito: o ranking soma POR PESSOA, e ter que passar por
  -- `metas` pra descobrir de quem é cada marco tornaria a query do placar um join
  -- sobre a tabela que a RLS mais protege.
  user_id     uuid not null,
  -- 1 = primeiro aporte ("você começou"), independente de percentual. Os outros são
  -- o percentual mesmo. O 10 existe por causa da meta grande: em R$ 100.000, o 25%
  -- ainda é R$ 25.000 — longe demais pra ser o primeiro sinal de vida.
  marco       smallint not null check (marco in (1, 10, 25, 50, 75, 90, 100)),
  atingido_em timestamptz not null default now(),
  -- CONGELADO no instante da conquista, nunca recalculado na leitura. A dificuldade
  -- é editável; se o ranking recalculasse, trocar "fácil" por "difícil" hoje
  -- reescreveria pontos ganhos meses atrás — o placar mudaria no passado.
  pontos      integer not null,
  -- Celebra uma vez, e só. É esta linha que impede o app de comemorar o mesmo 50%
  -- toda vez que a pessoa abre a tela, ou de recomemorar depois de um resgate.
  unique (meta_id, marco)
);

create index if not exists meta_marcos_user_idx on public.meta_marcos (user_id, atingido_em);

alter table public.meta_marcos enable row level security;

-- SELECT apenas, e só o próprio. Quem escreve é a trigger (security definer): marco
-- não é coisa que o cliente declara, é consequência de lançamento. Sem policy de
-- insert/update/delete, ninguém se auto-premia com um PATCH.
drop policy if exists "meta_marcos_select_own" on public.meta_marcos;
create policy "meta_marcos_select_own" on public.meta_marcos
  for select to authenticated using (user_id = auth.uid());

-- ============================================================================
-- 3. A trigger — agora marca conclusão E marcos
-- ============================================================================
-- Continua sendo UMA função no banco, e não regra no cliente, pelo mesmo motivo de
-- 16/09: o aporte nasce de mais de um lugar, e regra replicada vira regras diferentes
-- no primeiro bug.
create or replace function public.metas_marca_conclusao()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  alvo_meta  bigint := coalesce(new.meta_id, old.meta_id);
  acumulado  numeric;
  alvo       numeric;
  dono       uuid;
  dific      text;
  peso       integer;
  progresso  numeric;
  pct        numeric;
  m          smallint;
  anterior   smallint;
  marcos     smallint[] := array[1, 10, 25, 50, 75, 90, 100];
begin
  if alvo_meta is null then
    return coalesce(new, old);
  end if;

  -- Guardado menos resgatado. Conta aporte que não abate do saldo também
  -- (2026-09-18): a caixinha enche igual, o troféu é sobre ela ter enchido e não
  -- sobre de qual bolso o dinheiro veio.
  select coalesce(sum(case when l.tipo = 'gasto' then l.valor else -l.valor end), 0)
    into acumulado
    from public."Lancamentos" l
   where l.meta_id = alvo_meta;

  select m2.valor_alvo, m2.user_id, m2.dificuldade
    into alvo, dono, dific
    from public.metas m2
   where m2.id = alvo_meta;

  if alvo is null or alvo <= 0 then
    return coalesce(new, old);
  end if;

  -- Pesos inteiros (2/3/4) e não 1/1,5/2 pra os pontos fecharem sem arredondamento.
  -- A PROPORÇÃO é a mesma: difícil vale o dobro de fácil, moderada vale 1,5×.
  --
  -- E é 2× e não 3× de propósito: com 3, marcar "difícil" seria bom demais pra
  -- recusar, e aí todo mundo marca difícil e o multiplicador deixa de diferenciar
  -- qualquer coisa. A diferença precisa existir sem dominar.
  peso := case dific when 'facil' then 2 when 'dificil' then 4 else 3 end;

  progresso := acumulado / alvo;
  pct := progresso * 100;

  -- ===== Conclusão (regra de 16/09, intacta) =====
  if acumulado >= alvo then
    -- `is null` no where: só a PRIMEIRA vez. Bater o alvo de novo depois de um
    -- resgate não reescreve a data — o troféu é do dia em que foi conquistado.
    update public.metas set concluida_em = now()
     where id = alvo_meta and concluida_em is null;
  end if;

  -- ===== Progresso máximo: sobe, nunca desce =====
  update public.metas
     set progresso_max = greatest(progresso_max, progresso)
   where id = alvo_meta;

  -- ===== Marcos =====
  foreach m in array marcos loop
    -- O marco 1 é "começou": basta ter entrado dinheiro, qualquer valor. Um aporte
    -- de R$ 10 numa meta de R$ 100.000 é 0,01% — e ainda assim é o dia em que a
    -- pessoa começou, que é o que o marco existe pra marcar.
    if (m = 1 and acumulado > 0) or (m > 1 and pct >= m) then
      -- `anterior` é o marco imediatamente abaixo: os pontos de um marco são o
      -- INCREMENTO que ele representa, pra soma dos sete fechar exatamente
      -- 100 × peso (fácil 200, moderada 300, difícil 400).
      anterior := case m when 1 then 0 when 10 then 1 when 25 then 10 when 50 then 25
                         when 75 then 50 when 90 then 75 else 90 end;

      insert into public.meta_marcos (meta_id, user_id, marco, pontos)
      values (alvo_meta, dono, m, (m - anterior) * peso)
      on conflict (meta_id, marco) do nothing;   -- já celebrado: passa batido
    end if;
  end loop;

  update public.metas
     set marco_max = coalesce((select max(mm.marco) from public.meta_marcos mm where mm.meta_id = alvo_meta), 0)
   where id = alvo_meta;

  return coalesce(new, old);
end;
$$;

-- A trigger em si não muda (mesma função, mesmos eventos) — recriada só por garantia
-- de que existe, já que `create or replace function` sozinho não a cria.
drop trigger if exists trg_metas_conclusao on public."Lancamentos";
create trigger trg_metas_conclusao
  after insert or update or delete on public."Lancamentos"
  for each row execute function public.metas_marca_conclusao();

-- ============================================================================
-- 4. Backfill — quem já tem meta não pode começar zerado
-- ============================================================================
-- Sem isto, quem já guardou dinheiro veria `marco_max = 0` e o app comemoraria os
-- marcos antigos um por um no próximo aporte, como se tivessem acabado de acontecer.
-- O UPDATE abaixo é um no-op que só existe pra disparar a trigger em cada meta que já
-- tem lançamento — reusa a mesma lógica em vez de reimplementá-la aqui.
update public."Lancamentos"
   set meta_id = meta_id
 where meta_id is not null;

-- Os marcos do backfill ficam com `atingido_em = now()`, e não com a data real do
-- lançamento que os causou. É aceitável: a base tem poucos usuários e nenhum ranking
-- no ar ainda. De hoje em diante a data é a de verdade.

-- ============================================================================
-- Conferir depois de rodar
-- ============================================================================
--   select nome, dificuldade, progresso_max, marco_max, concluida_em from public.metas;
--   select meta_id, marco, pontos, atingido_em from public.meta_marcos order by meta_id, marco;
--   select conname from pg_constraint where conname = 'metas_dificuldade_valida';
--   -- soma por pessoa (o esqueleto do ranking):
--   select user_id, sum(pontos) from public.meta_marcos group by 1 order by 2 desc;
