-- 2026-09-16 — METAS (caixinhas de guardar dinheiro), Fase 1
--
-- Brief: Chave Mestre, Projetos/PRADEX/briefs/2026-09-16_metas-caixinhas.md
--
-- Caixinha de guardar dinheiro. A pessoa cria "Viagem — R$ 5.000", registra que
-- guardou, a barra enche, e no 100% a meta é concluída. `concluida_em` é o troféu que
-- o ranking (brief à parte) vai contar.
--
-- DECISÃO CENTRAL (Lucas, 16/09): guardar = aplicar = DEBITAR DA CONTA. O aporte é um
-- lançamento de verdade e sai do saldo do mês, como sai na vida real. Por isso NÃO
-- existe tabela de aportes: o histórico da caixinha É o histórico de lançamentos com
-- `meta_id`. Uma fonte da verdade, zero risco de as duas divergirem.
--
--   guardar R$ 500  -> Lancamentos tipo 'gasto',   meta_id = X  (sai do saldo)
--   resgatar R$ 200 -> Lancamentos tipo 'receita', meta_id = X  (volta pro saldo)
--
-- O aporte reusa `tipo = 'gasto'` em vez de um terceiro tipo porque
-- `tipo === "gasto"/"receita"` aparece 46× em 4 arquivos do front mais o enum da tool
-- da Edge Function — um ponto esquecido faria o dinheiro guardado sumir de um total
-- sem dar erro nenhum. Reusando, o débito acontece nos 46 pontos de graça e só quem
-- precisa separar consumo de poupança filtra por `meta_id`.

-- ============================================================================
-- 1. metas
-- ============================================================================
create table if not exists public.metas (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  nome         text not null,
  valor_alvo   numeric(12,2) not null check (valor_alvo > 0),
  -- Onde o dinheiro está guardado, texto livre ("caixinha do Nubank", "CDB Inter").
  -- É anotação do dono: o app não interpreta, não valida e não concilia com nada.
  -- O Pradex nunca lê conta — quem diz que guardou é a pessoa.
  aplicado_em  text,
  prazo        date,
  icone        text,
  -- O troféu. Escrito UMA vez, quando o acumulado cruza valor_alvo, e nunca desfeito
  -- por resgate posterior: se oscilasse, o ranking viraria placar piscando.
  concluida_em timestamptz,
  arquivada    boolean not null default false,
  criada_em    timestamptz not null default now()
);

-- ⚠️ `create table if not exists` garante EXISTÊNCIA, não FORMATO. Se a tabela já
-- existir em produção com menos colunas, o bloco acima é NO-OP silencioso e o app
-- passa dias escrevendo contra coluna inexistente (PGRST204) — foi exatamente o que
-- aconteceu com `orcamentos` entre 12 e 14/09. Daí os alters explícitos:
alter table public.metas add column if not exists aplicado_em  text;
alter table public.metas add column if not exists prazo        date;
alter table public.metas add column if not exists icone        text;
alter table public.metas add column if not exists concluida_em timestamptz;
alter table public.metas add column if not exists arquivada    boolean not null default false;

create index if not exists metas_user_idx on public.metas (user_id);

-- Duas caixinhas com o mesmo nome viram confusão no WhatsApp ("guardei 200 na
-- viagem" — qual?). Só vale pras ativas: arquivar e recriar com o mesmo nome pode.
create unique index if not exists metas_user_nome_ativa_idx
  on public.metas (user_id, lower(nome))
  where arquivada = false;

-- ============================================================================
-- 2. O vínculo em Lancamentos
-- ============================================================================
-- Nullable: a esmagadora maioria dos lançamentos não é aporte.
-- on delete set null: apagar a meta não pode levar o lançamento junto — o dinheiro
-- saiu da conta de qualquer jeito, e sumir com ele falsearia o mês fechado.
alter table public."Lancamentos"
  add column if not exists meta_id bigint references public.metas (id) on delete set null;

create index if not exists lancamentos_meta_idx
  on public."Lancamentos" (meta_id) where meta_id is not null;

-- ============================================================================
-- 3. O troféu, por trigger
-- ============================================================================
-- Fica no banco e não na tela porque o aporte pode nascer de três lugares (tela de
-- Metas, tela de Lançar, WhatsApp). Regra de conclusão replicada em três clientes
-- vira três regras diferentes no primeiro bug.
create or replace function public.metas_marca_conclusao()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  alvo_meta bigint := coalesce(new.meta_id, old.meta_id);
  acumulado numeric;
  alvo      numeric;
begin
  if alvo_meta is null then
    return coalesce(new, old);
  end if;

  -- Guardado menos resgatado. O filtro por user_id é defesa em profundidade: a RLS
  -- já isola, mas esta função é SECURITY DEFINER e roda sem ela.
  select coalesce(sum(case when l.tipo = 'gasto' then l.valor else -l.valor end), 0)
    into acumulado
    from public."Lancamentos" l
   where l.meta_id = alvo_meta;

  select m.valor_alvo into alvo from public.metas m where m.id = alvo_meta;

  if alvo is not null and acumulado >= alvo then
    -- `is null` no where: só a PRIMEIRA vez. Bater o alvo de novo depois de um
    -- resgate não reescreve a data — o troféu é do dia em que foi conquistado.
    update public.metas set concluida_em = now()
     where id = alvo_meta and concluida_em is null;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_metas_conclusao on public."Lancamentos";
create trigger trg_metas_conclusao
  after insert or update or delete on public."Lancamentos"
  for each row execute function public.metas_marca_conclusao();

-- ============================================================================
-- 4. RLS
-- ============================================================================
alter table public.metas enable row level security;

drop policy if exists "metas_select_own" on public.metas;
create policy "metas_select_own" on public.metas
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "metas_insert_own" on public.metas;
create policy "metas_insert_own" on public.metas
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "metas_update_own" on public.metas;
create policy "metas_update_own" on public.metas
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "metas_delete_own" on public.metas;
create policy "metas_delete_own" on public.metas
  for delete to authenticated using (user_id = auth.uid());

-- Nenhuma exceção pra leitura cross-usuário aqui. O ranking (brief à parte) vai
-- precisar disso, e vai entrar por RPC `security definer` devolvendo só apelido e
-- contagem — nunca afrouxando estas policies.

-- ============================================================================
-- Conferir depois de rodar
-- ============================================================================
--   select column_name from information_schema.columns
--    where table_schema = 'public' and table_name = 'metas' order by ordinal_position;
--
--   select column_name from information_schema.columns
--    where table_schema = 'public' and table_name = 'Lancamentos' and column_name = 'meta_id';
--
--   select policyname from pg_policies where schemaname = 'public' and tablename = 'metas';
--
--   -- a trigger existe?
--   select tgname from pg_trigger where tgname = 'trg_metas_conclusao';
