-- 2026-09-19 (f) — CUTUCADA: o Pradex fala primeiro
--
-- A correção do Lucas, e ela inverte o que eu tinha construído de manhã:
--
--   "esses modos não é o cliente que vai falar, é o Pradex que vai instigar"
--
-- Eu li o modo caos como REATIVO — o cliente manda mensagem, o agente responde com
-- sarcasmo. Mas a frase original dele já dizia o contrário: "o modo caos pode ter
-- direcionamento da META na hora de mandar uma CHAMADA no cliente". Chamada é o
-- Pradex chamando. O tom reativo continua valendo; o que faltava é o Pradex abrir a
-- boca sozinho.
--
-- ============================================================================
-- Esta tabela existe pra o Pradex NÃO virar spam
-- ============================================================================
-- Um agente que provoca é bom uma vez por semana e insuportável todo dia. E o custo
-- de errar aqui não é uma métrica pior: é a pessoa bloquear o número, e aí nem o
-- lançamento por WhatsApp funciona mais — o produto inteiro morre junto.
--
-- Por isso cada cutucada vira linha, e as duas travas de frequência leem daqui:
--   1. no máximo uma cutucada por pessoa a cada 3 dias;
--   2. o MESMO gatilho sobre a MESMA coisa, no máximo a cada 14 dias.
--
-- A segunda é a que impede "sua meta Viagem está parada" todo santo dia pra quem
-- decidiu pausar aquela meta de propósito.

create table if not exists public.agente_cutucadas (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  -- teto_estourado | teto_90 | meta_parada | meta_risco | meta_concluida
  gatilho    text not null,
  -- Sobre O QUÊ: o nome da categoria ou da meta. É o que distingue "Delivery
  -- estourou" de "Transporte estourou" — sem isto, avisar de uma categoria
  -- bloquearia o aviso de todas as outras por 14 dias.
  referencia text not null,
  tom        text,
  mensagem   text,
  enviada_em timestamptz not null default now()
);

create index if not exists agente_cutucadas_user_idx
  on public.agente_cutucadas (user_id, enviada_em desc);

create index if not exists agente_cutucadas_repeticao_idx
  on public.agente_cutucadas (user_id, gatilho, referencia, enviada_em desc);

alter table public.agente_cutucadas enable row level security;

-- Sem policy nenhuma: quem escreve e lê é a Edge Function com service role, que
-- ignora RLS. O cliente não precisa ver esta tabela, e a ausência de policy é a
-- forma mais curta de garantir que ele não veja.

-- ============================================================================
-- Conferir depois de rodar
-- ============================================================================
--   select gatilho, referencia, tom, enviada_em from public.agente_cutucadas
--    order by enviada_em desc limit 20;
--
--   -- quem foi cutucado nos últimos 3 dias (é o filtro que a função aplica):
--   select user_id, max(enviada_em) from public.agente_cutucadas
--    where enviada_em > now() - interval '3 days' group by 1;
