-- 2026-09-14 — Recria `orcamentos` do zero, com o formato certo
--
-- HISTÓRIA CURTA. Existia em produção uma tabela `orcamentos` de um desenho antigo,
-- NUNCA usada. Quando a migration de 12/09 rodou com `create table if not exists`,
-- ela virou no-op silencioso e o app passou a escrever contra um formato que não era
-- o dele. Sintoma: "o teto some".
--
-- A migration anterior (2026-09-14_orcamentos_colunas_faltando.sql) acrescentou as
-- colunas que faltavam — `limite` e `updated_at`, hoje presentes. Mas sobrou o que
-- `add column` não conserta: a coluna `mes` é INTEGER, e o desenho pede DATE (o dia 1
-- do mês de competência). Confirmado pela API:
--
--   POST mes = "2026-09-17"  → 22P02 invalid input syntax for type integer
--   POST mes = 9             → function date_trunc(unknown, integer) does not exist
--
-- POR QUE DROP E NÃO ALTER. A tabela está VAZIA — `content-range: */0` na API, com a
-- sessão real. Sem dado pra preservar, recriar é mais honesto que empilhar ALTERs: o
-- resultado final é exatamente a definição de 12/09, sem herança de formato velho.
--
-- ⚠️ Se algum dia esta migration for reaplicada num banco COM dados, o drop leva tudo.
-- Ela é específica deste conserto e deve rodar uma vez só.

-- ============================================================================
-- 1. Fora o antigo
-- ============================================================================
-- cascade derruba junto os índices, policies e o trigger que penduraram nela.
drop table if exists public.orcamentos cascade;

-- ============================================================================
-- 2. O formato certo (idêntico ao de 2026-09-12_orcamentos.sql)
-- ============================================================================
create table public.orcamentos (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  categoria   text not null,
  -- numeric, nunca float: dinheiro não arredonda sozinho.
  limite      numeric(12,2) not null check (limite > 0),
  -- Primeiro dia do mês de competência. DATE (e não ano+mês em duas colunas, nem
  -- integer) deixa comparação e ordenação triviais — e é o que a herança de teto
  -- entre meses usa, com `mes <= :mes_atual order by mes desc`.
  mes         date not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index orcamentos_user_mes_idx
  on public.orcamentos (user_id, mes);

-- Um teto por categoria por mês. `lower()` porque a categoria é texto livre do
-- cadastro do usuário — "Delivery" e "delivery" são a mesma coisa.
create unique index orcamentos_user_mes_categoria_idx
  on public.orcamentos (user_id, mes, lower(categoria));

-- O mês é sempre o dia 1. Sem isto, 2026-09-01 e 2026-09-15 viram dois orçamentos
-- distintos do mesmo mês e a unique acima não protege nada.
create or replace function public.orcamentos_normaliza()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.mes := date_trunc('month', new.mes)::date;
  new.categoria := btrim(new.categoria);
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_orcamentos_normaliza
  before insert or update on public.orcamentos
  for each row execute function public.orcamentos_normaliza();

-- ============================================================================
-- 3. RLS
-- ============================================================================
alter table public.orcamentos enable row level security;

create policy "orcamentos_select_own" on public.orcamentos
  for select to authenticated using (user_id = auth.uid());

create policy "orcamentos_insert_own" on public.orcamentos
  for insert to authenticated with check (user_id = auth.uid());

create policy "orcamentos_update_own" on public.orcamentos
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "orcamentos_delete_own" on public.orcamentos
  for delete to authenticated using (user_id = auth.uid());

-- ============================================================================
-- 4. PostgREST relê o schema
-- ============================================================================
-- Sem isto o erro continua mesmo com a tabela já certa: o PostgREST serve de cache.
notify pgrst, 'reload schema';

-- ============================================================================
-- Conferir
-- ============================================================================
--   select column_name, data_type
--     from information_schema.columns
--    where table_schema = 'public' and table_name = 'orcamentos'
--    order by ordinal_position;
--
-- `mes` tem que aparecer como `date`, e `limite` como `numeric`.
