-- ============================================================
-- COLE NO SQL EDITOR DO SUPABASE E RODE DE UMA VEZ SO.
-- Gerado em 2026-09-13. Projeto sjvuhqqsjboncwpboclv.
--
-- 4 migrations pendentes, NA ORDEM CERTA. A ordem importa: a de premio
-- recria o trigger SEM acesso_pago, entao o drop vem antes.
--
-- Tudo idempotente (if exists / if not exists / create or replace):
-- rodar duas vezes nao quebra nada.
--
-- !! DEPOIS de rodar, e SO depois, rode tambem:
--      npx supabase functions deploy agente-pradex --project-ref sjvuhqqsjboncwpboclv
--      npx supabase functions deploy cakto-webhook  --project-ref sjvuhqqsjboncwpboclv
--    O agente novo exige a coluna email_verificado_em. Deployar antes de rodar
--    isto aqui QUEBRA o onboarding do WhatsApp pra todo mundo.
-- ============================================================


-- ▼▼▼ 2026-09-11_drop_acesso_pago.sql ▼▼▼

-- 2026-09-11 — Aposenta `fp_perfil.acesso_pago`
--
-- Item 9 do backlog de 07/09 ("limpar acesso_pago").
--
-- HISTÓRIA. A coluna nasceu em 2026-08-15 como o gate único dos dois recursos pagos
-- (agente WhatsApp + Diagnóstico FP), quando a esteira era Pradex 1:1 / Pradex 360 e a
-- liberação era UPDATE na mão. Em 2026-09-05 a Fase 0 do SaaS trouxe `plano`
-- ('none' | 'essencial' | 'assistente'), e desde então `acesso_pago` virou um espelho:
-- o trigger a mantinha como `plano = 'assistente'` e nada mais lia dela.
--
-- Em 2026-09-11 o PRADELLA aposentou a esteira 1:1/360 de vez — o que resta é
-- Free / Essencial / Assistente. A coluna perdeu o último motivo de existir.
--
-- SEM PERDA DE DADO. `acesso_pago` era 100% derivada de `plano`. Quem quiser o valor
-- antigo de volta calcula: `plano = 'assistente'`. Nenhuma policy, índice ou view
-- depende dela (conferido), e o front já não a menciona em lugar nenhum — só estas
-- migrations citavam.
--
-- ORDEM IMPORTA: a atribuição sai do trigger ANTES do drop, senão o próximo
-- insert/update estoura "column acesso_pago does not exist".

-- ============================================================================
-- 1. Trigger sem a sincronização
-- ============================================================================
-- Mesma função de 2026-09-07 (guarda de plano + trial), menos a linha do espelho.
create or replace function public.fp_perfil_sync_plano()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if current_user in ('anon', 'authenticated') then
    -- Reverte em silêncio em vez de dar erro: o app nunca manda essas colunas, então
    -- levantar exceção só quebraria o cadastro se algum payload mudar sem querer.
    if tg_op = 'INSERT' then
      new.plano := 'none';
      new.plano_ate := null;
      new.trial_inicio := null;
      new.trial_ate := null;
    else
      new.plano := old.plano;
      new.plano_ate := old.plano_ate;
      new.trial_inicio := old.trial_inicio;
      new.trial_ate := old.trial_ate;
    end if;
  end if;

  return new;
end;
$$;

-- ============================================================================
-- 2. A coluna
-- ============================================================================
alter table public.fp_perfil
  drop column if exists acesso_pago;

-- ============================================================================
-- Conferir depois de rodar
-- ============================================================================
-- Não deve voltar nenhuma linha:
--
--   select column_name from information_schema.columns
--    where table_schema = 'public' and table_name = 'fp_perfil'
--      and column_name = 'acesso_pago';
--
-- E o gate segue de pé por `plano`:
--
--   select user_id, nome, telefone, plano, plano_ate, trial_ate
--     from public.fp_perfil where plano <> 'none' or trial_ate is not null
--    order by plano_ate nulls last;


-- ▼▼▼ 2026-09-12_orcamentos.sql ▼▼▼

-- 2026-09-12 — Orçamento por categoria (teto mensal)
--
-- Spec: Chave Mestre, Projetos/PRADEX/orcamento-e-disciplina.md
--
-- O teto é o que destrava o resto: vira o componente de maior peso do score de
-- disciplina (45 de 145) e liga 2 dos 5 gatilhos do modo caos, que hoje não podem
-- disparar porque não existe teto pra estourar.
--
-- Recurso do plano 'essencial' pra cima. O ENFORCEMENT do plano NÃO mora aqui —
-- mora no front (src/lib/plano.js) e, pro agente, na Edge Function. RLS aqui só
-- garante que ninguém lê nem escreve o teto de outra pessoa.

-- ============================================================================
-- 1. Tabela
-- ============================================================================
create table if not exists public.orcamentos (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  categoria   text not null,
  -- Teto do mês, em reais. numeric, nunca float: dinheiro não arredonda sozinho.
  limite      numeric(12,2) not null check (limite > 0),
  -- Primeiro dia do mês de competência. Guardar o mês como DATE (e não ano+mês em
  -- duas colunas) deixa comparação e ordenação triviais.
  mes         date not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists orcamentos_user_mes_idx
  on public.orcamentos (user_id, mes);

-- Um teto por categoria por mês. `lower()` porque a categoria é texto livre vindo
-- do cadastro do usuário — "Delivery" e "delivery" são a mesma coisa.
create unique index if not exists orcamentos_user_mes_categoria_idx
  on public.orcamentos (user_id, mes, lower(categoria));

-- O mês é sempre o dia 1. Sem isto, 2026-09-01 e 2026-09-15 viram dois orçamentos
-- distintos do mesmo mês e a unique acima não protege nada.
create or replace function public.orcamentos_normaliza()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.mes := date_trunc('month', new.mes)::date;
  new.categoria := btrim(new.categoria);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_orcamentos_normaliza on public.orcamentos;
create trigger trg_orcamentos_normaliza
  before insert or update on public.orcamentos
  for each row execute function public.orcamentos_normaliza();

-- ============================================================================
-- 2. RLS
-- ============================================================================
alter table public.orcamentos enable row level security;

drop policy if exists "orcamentos_select_own" on public.orcamentos;
create policy "orcamentos_select_own" on public.orcamentos
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "orcamentos_insert_own" on public.orcamentos;
create policy "orcamentos_insert_own" on public.orcamentos
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "orcamentos_update_own" on public.orcamentos;
create policy "orcamentos_update_own" on public.orcamentos
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "orcamentos_delete_own" on public.orcamentos;
create policy "orcamentos_delete_own" on public.orcamentos
  for delete to authenticated using (user_id = auth.uid());

-- ============================================================================
-- 3. Rede de segurança: versiona a proteção que hoje só existe no banco vivo
-- ============================================================================
-- A auditoria de 2026-09-12 (briefs/2026-09-12_auditoria-seguranca.md) achou que
-- `fp_perfil`, `Lancamentos`, `cartoes` e `categorias` NÃO têm RLS em migration
-- nenhuma. Produção está protegida — verificado contra a API com a anon key: leitura
-- devolve [] e escrita bate em "violates row-level security policy" —, mas um banco
-- recriado a partir destas migrations nasceria ABERTO.
--
-- Este bloco é deliberadamente conservador: só age se a tabela existir e NÃO tiver
-- nenhuma policy. Em produção ele não faz nada (as policies já estão lá); num banco
-- novo, ele fecha a porta. Nunca sobrescreve policy existente — se a de produção for
-- diferente da que eu escreveria, ela vence.
do $$
declare
  t text;
  alvos text[] := array['fp_perfil', 'Lancamentos', 'cartoes', 'categorias'];
begin
  foreach t in array alvos loop
    if not exists (
      select 1 from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relname = t and c.relkind = 'r'
    ) then
      raise notice 'orcamentos.sql: tabela %.% nao existe, pulando', 'public', t;
      continue;
    end if;

    execute format('alter table public.%I enable row level security', t);

    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = t) then
      raise notice 'orcamentos.sql: % ja tem policy, nao mexo', t;
      continue;
    end if;

    raise notice 'orcamentos.sql: % SEM policy — criando as quatro por user_id', t;
    execute format($f$create policy %I on public.%I for select to authenticated using (user_id = auth.uid())$f$, t || '_select_own', t);
    execute format($f$create policy %I on public.%I for insert to authenticated with check (user_id = auth.uid())$f$, t || '_insert_own', t);
    execute format($f$create policy %I on public.%I for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())$f$, t || '_update_own', t);
    execute format($f$create policy %I on public.%I for delete to authenticated using (user_id = auth.uid())$f$, t || '_delete_own', t);
  end loop;
end $$;

-- Mesma lógica pra RPC: `agente_aplicar_acoes` é SECURITY DEFINER e aceita p_user_id
-- do chamador sem comparar com auth.uid(). Em produção o EXECUTE já está revogado
-- (a chamada devolve 42501), mas isso também não está versionado em lugar nenhum.
-- Revogar de novo é idempotente e barato.
do $$
begin
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
              where n.nspname = 'public' and p.proname = 'agente_aplicar_acoes') then
    revoke execute on function public.agente_aplicar_acoes(uuid, jsonb) from public, anon, authenticated;
  end if;
end $$;

-- ============================================================================
-- Conferir depois de rodar
-- ============================================================================
--   select tablename, policyname from pg_policies
--    where schemaname = 'public' and tablename in
--      ('orcamentos','fp_perfil','Lancamentos','cartoes','categorias')
--    order by tablename, policyname;
--
--   -- deve devolver zero linhas (ninguém além do dono executa):
--   select grantee from information_schema.routine_privileges
--    where routine_name = 'agente_aplicar_acoes' and grantee in ('anon','authenticated','PUBLIC');


-- ▼▼▼ 2026-09-12_premio_disciplina.sql ▼▼▼

-- 2026-09-12 — Prêmio por disciplina (uma vez na vida)
--
-- Regra: bateu 80 de disciplina, com piso de dias distintos com lançamento, ganha
-- 20% no PRIMEIRO mês + 14 dias de trial. Uma vez por usuário, na vida.
-- Lógica em src/lib/premio.js. Spec: Chave Mestre, Projetos/PRADEX/orcamento-e-disciplina.md
--
-- ⚠️ Depende de 2026-09-11_drop_acesso_pago.sql: a função recriada abaixo NÃO
-- sincroniza `acesso_pago`. Se aquela migration ainda não tiver rodado, a coluna
-- simplesmente para de ser atualizada — ninguém a lê desde 05/09, então é inócuo.

alter table public.fp_perfil
  add column if not exists premio_disciplina_em timestamptz;

comment on column public.fp_perfil.premio_disciplina_em is
  'Quando o usuário resgatou o prêmio por disciplina. Preenchido UMA vez; não-nulo significa que ele nunca mais é elegível, mesmo que volte pro Free.';

-- ============================================================================
-- Guarda: o usuário não se auto-premia
-- ============================================================================
-- Mesmo motivo de plano e trial: o front escreve em fp_perfil com o token do próprio
-- usuário, então sem guarda qualquer conta faria PATCH zerando `premio_disciplina_em`
-- e resgataria o prêmio de novo, quantas vezes quisesse.
--
-- A regra aqui é assimétrica de propósito: em UPDATE, o valor antigo só é restaurado
-- quando já existe. Se for null, deixa passar — é assim que o resgate legítimo grava
-- a primeira vez sem precisar de service_role. Uma vez gravado, vira imutável.
create or replace function public.fp_perfil_sync_plano()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if current_user in ('anon', 'authenticated') then
    if tg_op = 'INSERT' then
      new.plano := 'none';
      new.plano_ate := null;
      new.trial_inicio := null;
      new.trial_ate := null;
      new.premio_disciplina_em := null;
    else
      new.plano := old.plano;
      new.plano_ate := old.plano_ate;
      new.trial_inicio := old.trial_inicio;
      new.trial_ate := old.trial_ate;
      -- Só trava depois do primeiro resgate. Null continua gravável uma vez.
      if old.premio_disciplina_em is not null then
        new.premio_disciplina_em := old.premio_disciplina_em;
      end if;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_fp_perfil_sync_plano on public.fp_perfil;
create trigger trg_fp_perfil_sync_plano
  before insert or update on public.fp_perfil
  for each row execute function public.fp_perfil_sync_plano();

-- ============================================================================
-- Conferir
-- ============================================================================
--   -- quem já resgatou:
--   select user_id, nome, plano, premio_disciplina_em
--     from public.fp_perfil where premio_disciplina_em is not null
--    order by premio_disciplina_em desc;
--
--   -- devolver o prêmio pra alguém (suporte; roda como postgres, o trigger não barra):
--   update public.fp_perfil set premio_disciplina_em = null where telefone = '55...';


-- ▼▼▼ 2026-09-13_onboarding_email_verificado.sql ▼▼▼

-- 2026-09-13 — Onboarding do WhatsApp passa a exigir posse do e-mail
--
-- Achado 4 da auditoria de 2026-09-12 (briefs/2026-09-12_auditoria-seguranca.md).
--
-- O FURO. Até aqui, SABER o e-mail bastava pra vincular um WhatsApp a uma conta.
-- Se existisse conta sem `telefone` preenchido — conta antiga, ou cadastro que parou
-- no meio — qualquer um que soubesse o endereço respondia o desafio no próprio
-- WhatsApp e ligava o número dele àquela conta. Não promovia plano, mas passava a
-- usar o agente por ela e a ver os lançamentos nas respostas.
--
-- O CONSERTO. O agente manda um código de 6 dígitos pro e-mail (OTP do Supabase Auth,
-- sem serviço novo) e só vincula depois de conferir. Esta coluna guarda quando isso
-- aconteceu, e a etapa de LGPD recusa avançar sem ela.
--
-- ⚠️ Esta migration acompanha o código da Edge Function. Aplicar as duas juntas: sem
-- a coluna, o `setOnboardingState` do estado "aguardando_codigo" falha e ninguém
-- consegue mais vincular WhatsApp nenhum.

alter table public.agente_onboarding_estado
  add column if not exists email_verificado_em timestamptz;

comment on column public.agente_onboarding_estado.email_verificado_em is
  'Quando o dono do e-mail provou posse pelo código OTP. Nulo = não verificado; a etapa de LGPD recusa avançar sem isto.';

-- ============================================================================
-- Limpeza dos estados em trânsito
-- ============================================================================
-- Quem estava no meio do onboarding antigo está no estado "aguardando_lgpd" SEM
-- verificação — exatamente a situação que o guard novo recusa. Em vez de deixar essa
-- gente travada numa mensagem de erro, o estado é apagado e ela recomeça do e-mail.
-- É uma mensagem a mais pra pouca gente, contra um vínculo sem prova pra sempre.
delete from public.agente_onboarding_estado
 where estado_atual = 'aguardando_lgpd'
   and email_verificado_em is null;

-- ============================================================================
-- Conferir
-- ============================================================================
--   select telefone, estado_atual, email_candidato, email_verificado_em, tentativas
--     from public.agente_onboarding_estado order by updated_at desc;

